### Criar novo produto (POST)
POST https://localhost:7211/product
Content-Type: application/json
{
  "name": "TV",
  "price": 1000.00
}

### Atualizar produto (PUT)
PUT https://localhost:7211/product
Content-Type: application/json
{
  "id": 3,
  "name": "Camiseta Atualizada",
  "price": 59.90
}

### Atualizar nome de múltiplos produtos (reset para "Reseted Name")
PUT https://localhost:7211/products
Content-Type: application/json

[
  { "id": 4 },
  { "id": 5}
]

### Deletar produto (DELETE)
DELETE https://localhost:7211/product/3

### Obter produto por ID (GET)
GET https://localhost:7211/product/4

### Obter todos os produtos (GET)
GET https://localhost:7211/products

### Obter nome do produto por ID (GET)
GET https://localhost:7211/productName/4

### Obter quantidade de produtos por ID do produto (GET)
GET https://localhost:7211/count

### Criar novo review (POST)
POST https://localhost:7211/review
Content-Type: application/json
{
  "productId": 4,
  "rating": 5
}

### Deletar review (DELETE)
DELETE https://localhost:7211/review/2

### Obter todos os reviews (GET)
GET https://localhost:7211/reviews

